/** Owned job, level, clan and materia parameters; initial values adapted from ffxiv-gearing (MIT). */
export const statNames = {
  STR: "力量",
  DEX: "灵巧",
  INT: "智力",
  MND: "精神",
  VIT: "耐力",
  CRT: "暴击",
  DHT: "直击",
  DET: "信念",
  SKS: "技速",
  SPS: "咏速",
  TEN: "坚韧",
  PIE: "信仰",
  CMS: "作业精度",
  CRL: "加工精度",
  CP: "制作力",
  GTH: "获得力",
  PCP: "鉴别力",
  GP: "采集力",
  PDMG: "物理基本性能",
  MDMG: "魔法基本性能",
  DLY: "攻击间隔",
  main: "unreachable",
  secondary: "unreachable",
};
export const jobLevelModifiers = {
  50: {
    main: 202,
    sub: 341,
    div: 341,
    det: 202,
    detTrunc: 5,
    ap: 75,
    apTank: 53,
    hp: 14,
    vit: 11.2,
    vitTank: 15.5,
  },
  60: {
    main: 218,
    sub: 354,
    div: 600,
    det: 600,
    detTrunc: 2,
    ap: 100,
    apTank: 78,
    hp: 15,
    vit: 12.9,
    vitTank: 17.5,
  },
  70: {
    main: 292,
    sub: 364,
    div: 900,
    det: 900,
    detTrunc: 1,
    ap: 125,
    apTank: 105,
    hp: 17,
    vit: 14.0,
    vitTank: 18.8,
  },
  80: {
    main: 340,
    sub: 380,
    div: 1300,
    det: 1300,
    detTrunc: 1,
    ap: 165,
    apTank: 115,
    hp: 20,
    vit: 18.8,
    vitTank: 26.6,
  },
  90: {
    main: 390,
    sub: 400,
    div: 1900,
    det: 1900,
    detTrunc: 1,
    ap: 195,
    apTank: 156,
    hp: 30,
    vit: 24.3,
    vitTank: 34.6,
  },
  100: {
    main: 440,
    sub: 420,
    div: 2780,
    det: 2780,
    detTrunc: 1,
    ap: 237,
    apTank: 190,
    hp: 40,
    vit: 30.1,
    vitTank: 43.0,
  },
};
export const jobLevels = Object.keys(jobLevelModifiers).map((l) => Number(l));
const jobLevelMax = jobLevels[jobLevels.length - 1];
export const baseStats = {
  STR: "main",
  DEX: "main",
  INT: "main",
  MND: "main",
  VIT: "main",
  CRT: "sub",
  DHT: "sub",
  DET: "main",
  SKS: "sub",
  SPS: "sub",
  TEN: "sub",
  PIE: "main",
  CMS: 0,
  CRL: 0,
  CP: 180,
  GTH: 0,
  PCP: 0,
  GP: 400,
};
export const customStatMax = 1000;
const statSchemas = {
  tank: ["STR", "CRT", "DET", "DHT", "SKS", "TEN", "VIT"],
  healer: ["MND", "CRT", "DET", "DHT", "SPS", "PIE", "VIT"],
  dpsStr: ["STR", "CRT", "DET", "DHT", "SKS", "VIT"],
  dpsDex: ["DEX", "CRT", "DET", "DHT", "SKS", "VIT"],
  dpsInt: ["INT", "CRT", "DET", "DHT", "SPS", "VIT"],
  crafting: ["CMS", "CRL", "CP"],
  gathering: ["GTH", "PCP", "GP"],
};
const slotSchemaCommon = [
  { slot: 3, name: "头部防具", uiGroup: "left" },
  { slot: 4, name: "身体防具", uiGroup: "left" },
  { slot: 5, name: "手部防具", uiGroup: "left" },
  { slot: 7, name: "腿部防具", uiGroup: "left" },
  { slot: 8, name: "脚部防具", uiGroup: "left" },
  { slot: 9, name: "耳饰", uiGroup: "right" },
  { slot: 10, name: "项链", uiGroup: "right" },
  { slot: 11, name: "手镯", uiGroup: "right" },
  { slot: 12, name: "戒指", uiGroup: "right" },
  { slot: -12, name: "戒指", uiGroup: "right" },
  { slot: -1, name: "食品", levelWeight: 0, uiGroup: "misc" },
];
const slotSchemaCombat = [
  { slot: 13, name: "武器", levelWeight: 2, uiGroup: "weapon" },
  ...slotSchemaCommon,
];
const slotSchemaGathering = [
  { slot: 1, name: "主工具", shortName: "主手", uiGroup: "weapon" },
  { slot: 2, name: "副工具", shortName: "副手", uiGroup: "weapon" },
  ...slotSchemaCommon,
];
const slotSchemaCrafting = [
  ...slotSchemaGathering.slice(0, -1),
  {
    slot: 17,
    name: "灵魂水晶",
    shortName: "水晶",
    levelWeight: 0,
    uiGroup: "misc",
  },
  slotSchemaGathering[slotSchemaGathering.length - 1],
  { slot: -2, name: "药品", levelWeight: 0, uiGroup: "misc" },
];
const defaultItemLevelCombat = [780, 795];
const defaultItemLevelCrafting = [750, 780];
const defaultItemLevelGathering = defaultItemLevelCrafting;
export const jobSchemas = {
  PLD: {
    name: "骑士",
    stats: statSchemas.tank,
    slots: [
      { slot: 1, name: "武器", uiGroup: "weapon" },
      { slot: 2, name: "盾牌", uiGroup: "weapon" },
      ...slotSchemaCommon,
    ],
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { STR: 100, VIT: 110, hp: 140 },
    mainStat: "VIT",
    secondaryStat: "TEN",
    traitDamageMultiplier: 1,
  },
  WAR: {
    name: "战士",
    stats: statSchemas.tank,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { STR: 105, VIT: 110, hp: 145 },
    mainStat: "VIT",
    secondaryStat: "TEN",
    traitDamageMultiplier: 1,
  },
  DRK: {
    name: "暗黑骑士",
    stats: statSchemas.tank,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { STR: 105, VIT: 110, hp: 140 },
    mainStat: "VIT",
    secondaryStat: "TEN",
    traitDamageMultiplier: 1,
  },
  GNB: {
    name: "绝枪战士",
    stats: statSchemas.tank,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { STR: 100, VIT: 110, hp: 140 },
    mainStat: "VIT",
    secondaryStat: "TEN",
    traitDamageMultiplier: 1,
  },
  WHM: {
    name: "白魔法师",
    stats: statSchemas.healer,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { MND: 115, VIT: 100, hp: 105 },
    mainStat: "MND",
    secondaryStat: "PIE",
    traitDamageMultiplier: 1.3,
  },
  SCH: {
    name: "学者",
    stats: statSchemas.healer,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { MND: 115, VIT: 100, hp: 105 },
    mainStat: "MND",
    secondaryStat: "PIE",
    traitDamageMultiplier: 1.3,
  },
  AST: {
    name: "占星术士",
    stats: statSchemas.healer,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { MND: 115, VIT: 100, hp: 105 },
    mainStat: "MND",
    secondaryStat: "PIE",
    traitDamageMultiplier: 1.3,
  },
  SGE: {
    name: "贤者",
    stats: statSchemas.healer,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { MND: 115, VIT: 100, hp: 105 },
    mainStat: "MND",
    secondaryStat: "PIE",
    traitDamageMultiplier: 1.3,
  },
  MNK: {
    name: "武僧",
    stats: statSchemas.dpsStr,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: {
      STR: 110,
      VIT: 100,
      hp: 110,
      gcd: 80,
      gcdReason: "“疾风迅雷”状态中",
    },
    mainStat: "STR",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1,
  },
  DRG: {
    name: "龙骑士",
    stats: statSchemas.dpsStr,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { STR: 115, VIT: 105, hp: 115 },
    mainStat: "STR",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1,
  },
  NIN: {
    name: "忍者",
    stats: statSchemas.dpsDex,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: {
      DEX: 110,
      VIT: 100,
      hp: 108,
      gcd: 85,
      gcdReason: "“风遁”状态中",
    },
    mainStat: "DEX",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1,
  },
  SAM: {
    name: "武士",
    stats: statSchemas.dpsStr,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: {
      STR: 112,
      VIT: 100,
      hp: 109,
      gcd: 87,
      gcdReason: "“风花”状态中",
    },
    mainStat: "STR",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1,
  },
  RPR: {
    name: "钐镰客",
    stats: statSchemas.dpsStr,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { STR: 115, VIT: 105, hp: 115 },
    mainStat: "STR",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1,
  },
  VPR: {
    name: "蝰蛇剑士",
    stats: statSchemas.dpsDex,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: {
      DEX: 110,
      VIT: 100,
      hp: 111,
      gcd: 85,
      gcdReason: "“疾速”状态中",
    },
    mainStat: "DEX",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1,
  },
  BRD: {
    name: "吟游诗人",
    stats: statSchemas.dpsDex,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { DEX: 115, VIT: 100, hp: 105 },
    mainStat: "DEX",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1.2,
  },
  MCH: {
    name: "机工士",
    stats: statSchemas.dpsDex,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { DEX: 115, VIT: 100, hp: 105 },
    mainStat: "DEX",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1.2,
  },
  DNC: {
    name: "舞者",
    stats: statSchemas.dpsDex,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { DEX: 115, VIT: 100, hp: 105 },
    mainStat: "DEX",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1.2,
  },
  BLM: {
    name: "黑魔法师",
    stats: statSchemas.dpsInt,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { INT: 115, VIT: 100, hp: 105 },
    mainStat: "INT",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1.3,
  },
  SMN: {
    name: "召唤师",
    stats: statSchemas.dpsInt,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { INT: 115, VIT: 100, hp: 105 },
    mainStat: "INT",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1.3,
  },
  RDM: {
    name: "赤魔法师",
    stats: statSchemas.dpsInt,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { INT: 115, VIT: 100, hp: 105 },
    mainStat: "INT",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1.3,
  },
  PCT: {
    name: "绘灵法师",
    stats: statSchemas.dpsInt,
    slots: slotSchemaCombat,
    defaultItemLevel: defaultItemLevelCombat,
    jobLevel: jobLevelMax,
    levelSyncable: true,
    statModifiers: { INT: 115, VIT: 100, hp: 105 },
    mainStat: "INT",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1.3,
  },
  BLU: {
    name: "青魔法师",
    stats: statSchemas.dpsInt,
    slots: [
      { slot: 13, name: "武器", levelWeight: 0, uiGroup: "weapon" },
      ...slotSchemaCommon,
    ],
    defaultItemLevel: [520, 530],
    jobLevel: 80,
    levelSyncable: true,
    statModifiers: { INT: 115, VIT: 100, hp: 105 },
    mainStat: "INT",
    secondaryStat: "DHT",
    traitDamageMultiplier: 1.5,
    partyBonus: 1.01,
  },
  CRP: {
    name: "刻木匠",
    stats: statSchemas.crafting,
    slots: slotSchemaCrafting,
    defaultItemLevel: defaultItemLevelCrafting,
    jobLevel: jobLevelMax,
    skeletonGears: true,
    toolMateriaDuplicates: 8,
  },
  BSM: {
    name: "锻铁匠",
    stats: statSchemas.crafting,
    slots: slotSchemaCrafting,
    defaultItemLevel: defaultItemLevelCrafting,
    jobLevel: jobLevelMax,
    skeletonGears: true,
    toolMateriaDuplicates: 8,
  },
  ARM: {
    name: "铸甲匠",
    stats: statSchemas.crafting,
    slots: slotSchemaCrafting,
    defaultItemLevel: defaultItemLevelCrafting,
    jobLevel: jobLevelMax,
    skeletonGears: true,
    toolMateriaDuplicates: 8,
  },
  GSM: {
    name: "雕金匠",
    stats: statSchemas.crafting,
    slots: slotSchemaCrafting,
    defaultItemLevel: defaultItemLevelCrafting,
    jobLevel: jobLevelMax,
    skeletonGears: true,
    toolMateriaDuplicates: 8,
  },
  LTW: {
    name: "制革匠",
    stats: statSchemas.crafting,
    slots: slotSchemaCrafting,
    defaultItemLevel: defaultItemLevelCrafting,
    jobLevel: jobLevelMax,
    skeletonGears: true,
    toolMateriaDuplicates: 8,
  },
  WVR: {
    name: "裁衣匠",
    stats: statSchemas.crafting,
    slots: slotSchemaCrafting,
    defaultItemLevel: defaultItemLevelCrafting,
    jobLevel: jobLevelMax,
    skeletonGears: true,
    toolMateriaDuplicates: 8,
  },
  ALC: {
    name: "炼金术士",
    stats: statSchemas.crafting,
    slots: slotSchemaCrafting,
    defaultItemLevel: defaultItemLevelCrafting,
    jobLevel: jobLevelMax,
    skeletonGears: true,
    toolMateriaDuplicates: 8,
  },
  CUL: {
    name: "烹调师",
    stats: statSchemas.crafting,
    slots: slotSchemaCrafting,
    defaultItemLevel: defaultItemLevelCrafting,
    jobLevel: jobLevelMax,
    skeletonGears: true,
    toolMateriaDuplicates: 8,
  },
  MIN: {
    name: "采矿工",
    stats: statSchemas.gathering,
    slots: slotSchemaGathering,
    defaultItemLevel: defaultItemLevelGathering,
    jobLevel: jobLevelMax,
    skeletonGears: true,
    toolMateriaDuplicates: 2,
  },
  BTN: {
    name: "园艺工",
    stats: statSchemas.gathering,
    slots: slotSchemaGathering,
    defaultItemLevel: defaultItemLevelGathering,
    jobLevel: jobLevelMax,
    skeletonGears: true,
    toolMateriaDuplicates: 2,
  },
  FSH: {
    name: "捕鱼人",
    stats: statSchemas.gathering,
    slots: slotSchemaGathering,
    defaultItemLevel: defaultItemLevelGathering,
    jobLevel: jobLevelMax,
    skeletonGears: true,
  },
};
export const statHighlight = {
  PIE: true,
  TEN: true,
  DHT: true,
  CRT: true,
  DET: true,
  SKS: true,
  SPS: true,
};
export const materias = {
  PIE: [1, 2, 3, 4, 6, 16, 8, 24, 12, 36, 18, 54],
  DHT: [1, 2, 3, 4, 6, 16, 8, 24, 12, 36, 18, 54],
  CRT: [1, 2, 3, 4, 6, 16, 8, 24, 12, 36, 18, 54],
  DET: [1, 2, 3, 4, 6, 16, 8, 24, 12, 36, 18, 54],
  SPS: [1, 2, 3, 4, 6, 16, 8, 24, 12, 36, 18, 54],
  SKS: [1, 2, 3, 4, 6, 16, 8, 24, 12, 36, 18, 54],
  TEN: [1, 2, 3, 4, 6, 16, 8, 24, 12, 36, 18, 54],
  CMS: [3, 4, 5, 6, 11, 16, 14, 21, 18, 27, 22, 33],
  CRL: [1, 2, 3, 4, 7, 10, 9, 13, 12, 18, 15, 23],
  CP: [1, 2, 3, 4, 6, 8, 7, 9, 8, 10, 9, 11],
  GTH: [3, 4, 5, 6, 10, 15, 12, 20, 14, 25, 20, 36],
  PCP: [3, 4, 5, 6, 10, 15, 12, 20, 14, 25, 20, 36],
  GP: [1, 2, 3, 4, 6, 8, 7, 9, 8, 10, 9, 11],
};
export const materiaGrades = [12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1];
export const materiaGradeRequiredLevels = [
  15, 30, 45, 70, 160, 290, 420, 420, 560, 560, 690, 690,
];
export const materiaGradeIsRestricted = Array.from(
  materiaGradeRequiredLevels,
  () => false,
);
for (const grade of [12, 10, 8, 6]) materiaGradeIsRestricted[grade] = true;
export const materiaSuccessRates = [
  [90, 82, 70, 58, 17, 17, 17, 17, 17, 17, 17, 17],
  [48, 44, 38, 32, 10, 0, 10, 0, 10, 0, 10, 0],
  [28, 26, 22, 20, 7, 0, 7, 0, 7, 0, 7, 0],
  [16, 16, 14, 12, 5, 0, 5, 0, 5, 0, 5, 0],
];
export const materiaNames = {
  CRT: "武略",
  DHT: "神眼",
  DET: "雄略",
  SKS: "战技",
  SPS: "咏唱",
  TEN: "刚柔",
  PIE: "信力",
  CMS: "名匠",
  CRL: "巨匠",
  CP: "魔匠",
  GTH: "达识",
  PCP: "博识",
  GP: "器识",
};
export const materiaGradeNames = [
  "壹",
  "贰",
  "叁",
  "肆",
  "伍",
  "陆",
  "柒",
  "捌",
  "玖",
  "拾",
  "拾壹",
  "拾贰",
];
export const races = [
  "人族",
  "精灵族",
  "拉拉菲尔族",
  "猫魅族",
  "鲁加族",
  "敖龙族",
  "硌狮族",
  "维埃拉族",
];
export const clans = [
  "中原之民",
  "高地之民",
  "森林之民",
  "黑影之民",
  "平原之民",
  "沙漠之民",
  "逐日之民",
  "护月之民",
  "北洋之民",
  "红焰之民",
  "晨曦之民",
  "暮晖之民",
  "掠日之民",
  "迷踪之民",
  "密林之民",
  "山林之民",
];
export const clanStats = {
  STR: [22, 23, 20, 20, 19, 19, 22, 19, 22, 20, 19, 23, 23, 23, 20, 19].map(
    (x) => x - 20,
  ),
  DEX: [19, 20, 23, 20, 23, 21, 23, 22, 19, 18, 22, 20, 17, 17, 23, 20].map(
    (x) => x - 20,
  ),
  VIT: [20, 22, 19, 19, 19, 18, 20, 18, 23, 23, 19, 22, 23, 23, 18, 19].map(
    (x) => x - 20,
  ),
  INT: [23, 18, 22, 23, 22, 22, 19, 21, 18, 20, 20, 20, 17, 17, 21, 23].map(
    (x) => x - 20,
  ),
  MND: [19, 20, 19, 21, 20, 23, 19, 23, 21, 22, 23, 18, 23, 23, 21, 22].map(
    (x) => x - 20,
  ),
};
export const syncLevelIsPopular = {
  345: true,
  375: true,
  475: true,
  605: true,
  635: true,
  735: true,
  795: true,
  300: true,
  700: true,
  665: true,
  695: true,
};
export const syncLevelOfJobLevels = {
  50: 130,
  60: 270,
  70: 400,
  80: 530,
  90: 660,
  100: 790,
};
