/** Translate owned, named coefficients into the shared frontend/native parameter contract. */
export function formulaRules(parameters, policy) {
  const g = parameters.gcd,
    e = parameters.effects;
  const c = e.critical,
    d = e.determination,
    h = e.directHit,
    t = e.tenacity;
  const formula = (numbers) => ({ numbers });
  return {
    floor: formula([parameters.roundingEpsilon]),
    calcGcd: formula([
      g.base,
      g.speedScale,
      g.timeUnits,
      g.baseDivisor,
      g.modifierLevel,
      g.defaultModifier,
      g.modifierDivisor,
      g.resultDivisor,
    ]),
    calcRequiredSpeed: formula(policy.requiredSpeedSearch),
    // Zero fallbacks and identity factors belong to the formula; variable game coefficients have names above.
    calcEffects: formula([
      e.blueMimicry,
      0,
      c.chanceScale,
      c.chanceBase,
      c.divisor,
      c.damageScale,
      c.damageBase,
      c.divisor,
      d.scale,
      d.base,
      d.divisor,
      h.chanceScale,
      h.divisor,
      t.damageScale,
      t.damageBase,
      t.divisor,
      t.mitigationScale,
      t.divisor,
      e.weaponDivisor,
      0,
      0,
      0,
      0,
      0,
      0,
      e.main.partyBonus,
      e.main.damageBase,
      e.main.divisor,
      e.potencyScale,
      1,
      1,
      h.damageBonus,
      1,
      e.speed.scale,
      e.speed.base,
      e.speed.divisor,
      e.mp.scale,
      e.mp.base,
    ]),
    getCaps: formula([parameters.capDivisor]),
  };
}
